//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdtSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OdtSharp.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;bool&gt;1|True|Yes|^OK|Up|Good|Fine)).
        /// </summary>
        internal static string rxBoolTrue {
            get {
                return ResourceManager.GetString("rxBoolTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutText	xhtml:about
        ///ActuateX	xlink:actuate
        ///AnchorType	text:anchor-type
        ///ApplyDesignMode	form:apply-design-mode
        ///AutomaticFocus	form:automatic-focus
        ///ClassNames	text:class-names
        ///ConditionalStyleName	text:cond-style-name
        ///ContentText	xhtml:content
        ///DataTypeText	xhtml:datatype
        ///DisplayOutlineLevel	text:display-outline-level
        ///DrawName	draw:name
        ///DrawStyleName	draw:style-name
        ///Global	text:global
        ///HeightSVG	svg:height
        ///Hyperlink	xlink:href
        ///Id	text:id
        ///LinkTypeX	xlink:type
        ///MimeType	draw:mime-type
        ///Name	text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tsvAttributeNameMap {
            get {
                return ResourceManager.GetString("tsvAttributeNameMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphabeticalIndex	text:alphabetical-index
        ///AlphabeticalIndexAutoMarkFile	text:alphabetical-index-auto-mark-file
        ///AlphabeticalIndexMark	text:alphabetical-index-mark
        ///AlphabeticalIndexMarkEnd	text:alphabetical-index-mark-end
        ///AlphabeticalIndexMarkStart	text:alphabetical-index-mark-start
        ///Anchor	text:a
        ///Annotation	office:annotation
        ///AnnotationEnd	office:annotation-end
        ///AuthorInitial	text:author-initials
        ///AuthorName	text:author-name
        ///Bibliography	text:bibliography
        ///BibliographyMark	text:bibliography-mark
        ///Bookm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tsvTextBlockTypeMap {
            get {
                return ResourceManager.GetString("tsvTextBlockTypeMap", resourceCulture);
            }
        }
    }
}
