/*
 * Copyright (c). 2026 Daniel Patterson, MCSD (danielanywhere).
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
 */

using System;
using System.Collections.Generic;
using System.Text;

namespace OdtSharp
{
	//*-------------------------------------------------------------------------*
	//*	TextBlockTypeEnum																												*
	//*-------------------------------------------------------------------------*
	/// <summary>
	/// Enumeration of recognized text block types.
	/// </summary>
	public enum TextBlockTypeEnum
	{
		None = 0,
		Text,
		AlphabeticalIndex,
		AlphabeticalIndexAutoMarkFile,
		AlphabeticalIndexMark,
		AlphabeticalIndexMarkEnd,
		AlphabeticalIndexMarkStart,
		Anchor,
		Annotation,
		AnnotationEnd,
		AuthorInitial,
		AuthorName,
		Bibliography,
		BibliographyMark,
		Bookmark,
		BookmarkEnd,
		BookmarkReference,
		BookmarkStart,
		Change,
		ChangeEnd,
		ChangeStart,
		Chapter,
		CharacterCount,
		ConditionalText,
		CreationDate,
		CreationTime,
		Creator,
		DatabaseDisplay,
		DatabaseName,
		DatabaseNext,
		DatabaseRowNumber,
		DatabaseRowSelect,
		DataPilotTable,
		Date,
		DateTime,
		DdeConnection,
		DdeConnectionGroup,
		DdeLink,
		Description,
		Draw3DScene,
		DrawAnchor,
		DrawCaption,
		DrawCircle,
		DrawConnector,
		DrawControl,
		DrawCustomShape,
		DrawEllipse,
		DrawFrame,
		DrawGroup,
		DrawLine,
		DrawMeasure,
		DrawPageThumbnail,
		DrawPath,
		DrawPolygon,
		DrawPolyline,
		DrawRect,
		DrawRegularPolygon,
		EditingCycles,
		EditingDuration,
		ExecuteMacro,
		Expression,
		Filename,
		Footer,
		Form,
		Header,
		Heading,
		HiddenParagraph,
		HiddenText,
		IllustrationIndex,
		ImageCount,
		InitialCreator,
		Keywords,
		LabelRange,
		LineBreak,
		List,
		Measure,
		Meta,
		MetaField,
		ModificationDate,
		ModificationTime,
		NamedExpression,
		Note,
		NoteRef,
		NumberedParagraph,
		ObjectCount,
		ObjectIndex,
		PageContinuation,
		PageCount,
		PageNumber,
		PageSequence,
		PageVariableGet,
		PageVariableSet,
		Paragraph,
		ParagraphCount,
		Placeholder,
		PrintDate,
		PrintedBy,
		PrintTime,
		ReferenceMark,
		ReferenceMarkEnd,
		ReferenceMarkStart,
		ReferenceRef,
		Ruby,
		Script,
		Section,
		SenderCity,
		SenderCompany,
		SenderCountry,
		SenderEmail,
		SenderFax,
		SenderFirstName,
		SenderInitials,
		SenderLastName,
		SenderPhonePrivate,
		SenderPhoneWork,
		SenderPosition,
		SenderPostalCode,
		SenderStateOrProvince,
		SenderStreet,
		SenderTitle,
		Sequence,
		SequenceDeclaration,
		SequenceRef,
		SheetName,
		SoftPageBreak,
		Space,
		Span,
		Subject,
		Tab,
		Table,
		TableCalculationSetting,
		TableConsolidation,
		TableContentValidation,
		TableCount,
		TableDatabaseRange,
		TableFormula,
		TableIndex,
		TableOfContents,
		TableOfContentsMark,
		TableOfContentsMarkEnd,
		TableOfContentsMarkStart,
		TemplateName,
		TextInput,
		Time,
		Title,
		TrackedChange,
		UserDefined,
		UserFieldDeclaration,
		UserFieldGet,
		UserFieldInput,
		UserIndex,
		UserIndexMark,
		UserIndexMarkEnd,
		UserIndexMarkStart,
		VariableDeclaration,
		VariableGet,
		VariableInput,
		VariableSet,
		WordCount
	}
	//*-------------------------------------------------------------------------*

}
